ALTER TABLE clips ADD COLUMN output_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clips ADD COLUMN output_height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clips ADD COLUMN output_hdr INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clips ADD COLUMN sdr_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clips ADD COLUMN sdr_height INTEGER NOT NULL DEFAULT 0;
