{{- $needS3 := and (eq .Values.outtake.storageBackend "s3") (not .Values.outtake.s3.existingSecret) }}
{{- $needDb := and (eq .Values.outtake.databaseBackend "postgres") (not .Values.outtake.existingSecret) .Values.outtake.databaseUrl }}
{{- if or $needS3 $needDb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outtake.fullname" . }}
  labels:
    {{- include "outtake.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needS3 }}
  s3-access-key: {{ .Values.outtake.s3.accessKey | quote }}
  s3-secret-key: {{ .Values.outtake.s3.secretKey | quote }}
  {{- end }}
  {{- if $needDb }}
  database-url: {{ .Values.outtake.databaseUrl | quote }}
  {{- end }}
{{- end }}
