// Copyright © 2026 - Nicholas Fedor <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlob creates a new instance of MockBlob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlob {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBlob{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBlob is an autogenerated mock type for the Blob type
type MockBlob struct {
	mock.Mock
}

type MockBlob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlob) EXPECT() *MockBlob_Expecter {
	return &MockBlob_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockBlob
func (_mock *MockBlob) DeleteFile(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlob_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockBlob_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - path string
func (_e *MockBlob_Expecter) DeleteFile(path any) *MockBlob_DeleteFile_Call {
	return &MockBlob_DeleteFile_Call{Call: _e.mock.On("DeleteFile", path)}
}

func (_c *MockBlob_DeleteFile_Call) Run(run func(path string)) *MockBlob_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlob_DeleteFile_Call) Return(err error) *MockBlob_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlob_DeleteFile_Call) RunAndReturn(run func(path string) error) *MockBlob_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type MockBlob
func (_mock *MockBlob) FileExists(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBlob_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type MockBlob_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - path string
func (_e *MockBlob_Expecter) FileExists(path any) *MockBlob_FileExists_Call {
	return &MockBlob_FileExists_Call{Call: _e.mock.On("FileExists", path)}
}

func (_c *MockBlob_FileExists_Call) Run(run func(path string)) *MockBlob_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlob_FileExists_Call) Return(b bool) *MockBlob_FileExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBlob_FileExists_Call) RunAndReturn(run func(path string) bool) *MockBlob_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBlob
func (_mock *MockBlob) Get(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlob_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlob_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockBlob_Expecter) Get(ctx any, path any) *MockBlob_Get_Call {
	return &MockBlob_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockBlob_Get_Call) Run(run func(ctx context.Context, path string)) *MockBlob_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlob_Get_Call) Return(err error) *MockBlob_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlob_Get_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockBlob_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockBlob
func (_mock *MockBlob) Put(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlob_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBlob_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockBlob_Expecter) Put(ctx any, path any) *MockBlob_Put_Call {
	return &MockBlob_Put_Call{Call: _e.mock.On("Put", ctx, path)}
}

func (_c *MockBlob_Put_Call) Run(run func(ctx context.Context, path string)) *MockBlob_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlob_Put_Call) Return(err error) *MockBlob_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlob_Put_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockBlob_Put_Call {
	_c.Call.Return(run)
	return _c
}

// WriteThumbnail provides a mock function for the type MockBlob
func (_mock *MockBlob) WriteThumbnail(id string, data []byte) error {
	ret := _mock.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteThumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlob_WriteThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteThumbnail'
type MockBlob_WriteThumbnail_Call struct {
	*mock.Call
}

// WriteThumbnail is a helper method to define mock.On call
//   - id string
//   - data []byte
func (_e *MockBlob_Expecter) WriteThumbnail(id any, data any) *MockBlob_WriteThumbnail_Call {
	return &MockBlob_WriteThumbnail_Call{Call: _e.mock.On("WriteThumbnail", id, data)}
}

func (_c *MockBlob_WriteThumbnail_Call) Run(run func(id string, data []byte)) *MockBlob_WriteThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlob_WriteThumbnail_Call) Return(err error) *MockBlob_WriteThumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlob_WriteThumbnail_Call) RunAndReturn(run func(id string, data []byte) error) *MockBlob_WriteThumbnail_Call {
	_c.Call.Return(run)
	return _c
}
