// Copyright (c) 2026 - Nicholas Fedor <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

package handlers

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	fiber "github.com/gofiber/fiber/v3"

	"github.com/PapagoLabs/outtake/internal/config"
)

// newPreviewTestHandler builds an HTMLHandler rooted at a throwaway storage dir.
//
// Parameters:
//   - t: Test context.
//
// Returns:
//   - handler: A handler ready to serve the preview route.
func newPreviewTestHandler(t *testing.T) *HTMLHandler {
	t.Helper()

	return NewHTMLHandler(
		nil,
		nil,
		nil,
		&config.Config{StoragePath: t.TempDir()},
		"outtake",
		"test",
	)
}

// getPreview issues a request for one preview id.
//
// Parameters:
//   - t: Test context.
//   - handler: Handler under test.
//   - id: Preview id taken from the request path.
//
// Returns:
//   - status: Response status code.
func getPreview(t *testing.T, handler *HTMLHandler, id string) int {
	t.Helper()

	app := fiber.New(fiber.Config{}) // the real app sets only ErrorHandler
	app.Get("/previews/:id", handler.PreviewFile)

	req := httptest.NewRequestWithContext(
		t.Context(),
		http.MethodGet,
		"/previews/"+id,
		nil,
	)

	resp, err := app.Test(req)
	require.NoError(t, err)

	t.Cleanup(func() { _ = resp.Body.Close() })

	return resp.StatusCode
}

// TestPreviewFileServesAValidID proves the guard does not break the real flow,
// where the id is a UUID generated by the preview handler.
func TestPreviewFileServesAValidID(t *testing.T) {
	t.Parallel()

	name := "1f0c3a52-8b6d-4e21-9a77-2c5d8e4f1b03"
	handler := newPreviewTestHandler(t)
	seedPreviewID(t, handler, name)

	assert.Equal(t, fiber.StatusOK, getPreview(t, handler, name))
}

// seedPreview creates the file PreviewFile would serve for an id, at exactly the
// path it builds when the id guard is absent.
//
// Without a file on disk the handler answers 404 for any id, so a rejection
// assertion over a missing file proves nothing about the guard. Seeding the
// real path means a 404 can only have come from the guard rejecting the id.
//
// Parameters:
//   - t: Test context.
//   - handler: Handler whose storage root is used.
func seedPreview(t *testing.T, handler *HTMLHandler) {
	t.Helper()

	dir := filepath.Join(handler.cfg.StoragePath, "previews")
	require.NoError(t, os.MkdirAll(dir, 0o750))
}

// seedPreviewID creates the preview file PreviewFile would serve for one id if
// the guard were absent.
//
// Without a file on disk the handler answers 404 for any id, so a rejection
// assertion over a missing file proves nothing about the guard. Writing the
// real target means a 404 can only have come from the guard rejecting the id.
//
// Parameters:
//   - t: Test context.
//   - handler: Handler whose storage root is used.
//   - id: Preview id; must not contain a raw path separator.
func seedPreviewID(t *testing.T, handler *HTMLHandler, id string) {
	t.Helper()

	seedPreview(t, handler)

	path := filepath.Join(handler.cfg.StoragePath, "previews", id+".mp4")
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o750))
	require.NoError(t, os.WriteFile(path, []byte("preview"), 0o600))
}

// TestPreviewFileRejectsUnsafeIDs covers the id shapes that could alter the
// resolved path, including the percent-encoded forms that survive Fiber's
// routing unescaped.
//
// Each id has a real file behind it at the path the handler builds, so the 404
// asserted here is the guard rejecting the id rather than the handler failing
// to find a file. Removing the guard fails this test for the plain and dotted
// ids, which are the cases where the guard is the only thing standing between
// the request and a served file. Ids carrying a path separator are covered by
// TestPreviewFileRejectsBeforeRouting.
func TestPreviewFileRejectsUnsafeIDs(t *testing.T) {
	t.Parallel()

	ids := []string{
		"..",
		"a.b",
		"a%00b",
		"a%20b",
		"..%2f..%2fetc%2fpasswd",
		"%2e%2e%2f%2e%2e%2fetc%2fpasswd",
		"%252e%252e%252fsecret",
		"..%5c..%5csecret",
	}

	for _, id := range ids {
		t.Run(id, func(t *testing.T) {
			t.Parallel()

			handler := newPreviewTestHandler(t)
			seedPreviewID(t, handler, id)

			assert.Equal(t, fiber.StatusNotFound, getPreview(t, handler, id),
				"the guard must reject the id even though the file exists")
		})
	}
}

// TestPreviewFileRejectsBeforeRouting covers ids carrying a path separator.
// These never reach the handler, because the router either normalises the path
// or refuses to match a multi-segment parameter, so they are asserted as
// routing behavior rather than as guard behavior.
func TestPreviewFileRejectsBeforeRouting(t *testing.T) {
	t.Parallel()

	ids := []string{
		"a/b",
		"../secret",
		"",
	}

	for _, id := range ids {
		t.Run(id, func(t *testing.T) {
			t.Parallel()

			handler := newPreviewTestHandler(t)
			seedPreview(t, handler)

			assert.Equal(t, fiber.StatusNotFound, getPreview(t, handler, id))
		})
	}
}

// TestPreviewFileRejectsOverlongID bounds the id so a long token cannot be used
// to probe the filesystem.
func TestPreviewFileRejectsOverlongID(t *testing.T) {
	t.Parallel()

	handler := newPreviewTestHandler(t)
	seedPreviewID(t, handler, longPreviewID(65))

	assert.Equal(t, fiber.StatusNotFound, getPreview(t, handler, longPreviewID(65)))
}

// TestValidPreviewID pins the accepted shape. The allowlist has to cover both
// the UUIDs used today and the content hashes planned for cached previews, so
// that a later switch to content-addressed ids does not need this revisited.
func TestValidPreviewID(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		give string
		want bool
	}{
		{name: "uuid", give: "1f0c3a52-8b6d-4e21-9a77-2c5d8e4f1b03", want: true},
		{
			name: "hex hash",
			give: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
			want: true,
		},
		{name: "base64url hash", give: "aB3-_xYz09", want: true},
		{name: "single character", give: "a", want: true},
		{name: "empty", give: "", want: false},
		{name: "parent segment", give: "..", want: false},
		{name: "traversal", give: "../secret", want: false},
		{name: "encoded traversal", give: "..%2f..%2fetc%2fpasswd", want: false},
		{name: "encoded dot", give: "%2e%2e", want: false},
		{name: "double encoded", give: "%252e%252e%252fsecret", want: false},
		{name: "encoded backslash", give: "..%5c..%5csecret", want: false},
		{name: "null byte", give: "a%00b", want: false},
		{name: "slash", give: "a/b", want: false},
		{name: "backslash", give: `a\b`, want: false},
		{name: "space", give: "a b", want: false},
		{name: "dot", give: "a.b", want: false},
		{name: "tilde", give: "~a", want: false},
		{name: "percent", give: "a%b", want: false},
		{name: "colon", give: "a:b", want: false},
		{name: "too long", give: longPreviewID(65), want: false},
		{name: "at the limit", give: longPreviewID(64), want: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, test.want, validPreviewID(test.give))
		})
	}
}

// longPreviewID builds an id of the requested length.
//
// Parameters:
//   - n: Number of characters.
//
// Returns:
//   - id: The generated id.
func longPreviewID(n int) string {
	return strings.Repeat("a", n)
}
