name: vet

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - main.go
      - go.mod
      - go.sum
      - internal/**
      - scripts/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.1020

      - name: Generate templ
        run: templ generate

      - name: Vet
        run: go vet ./...
